# Generated by Django 4.2.28 on 2026-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_remove_user_bio_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
