# Generated by Django 4.2.28 on 2026-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_user_days_user_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rate',
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.IntegerField(default=10000),
        ),
    ]
