# Generated by Django 4.2.28 on 2026-03-19 08:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_remove_user_days_remove_user_rate_user_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='salary',
            new_name='salary_before_taxes',
        ),
        migrations.AddField(
            model_name='user',
            name='military_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='pension_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.22'), max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='pit_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_after_taxes',
            field=models.IntegerField(default=0),
        ),
    ]
