# Generated by Django 4.2.28 on 2026-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_rename_salary_user_salary_before_taxes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary_before_taxes',
            field=models.IntegerField(default=0),
        ),
    ]
