# Generated by Django 4.2.11 on 2025-09-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='core.post',
        ),
    ]
