# Generated by Django 4.2.28 on 2026-03-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'core_category',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'core_language',
            },
        ),
        migrations.CreateModel(
            name='PostMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_label.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_label.language')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core_label.post')),
            ],
            options={
                'db_table': 'core_post_metadata',
                'unique_together': {('post', 'language', 'category')},
            },
        ),
    ]
