# Generated by Django 4.2.28 on 2026-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0003_category_language_postmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grammar',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='lexis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='phonetics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
