# Generated by Django 4.2.11 on 2025-09-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='core_post',
        ),
    ]
