# Generated by Django 4.2.28 on 2026-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0004_post_grammar_post_lexis_post_phonetics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='grammar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lexis',
        ),
        migrations.RemoveField(
            model_name='post',
            name='phonetics',
        ),
        migrations.AddField(
            model_name='post',
            name='linguistics_type',
            field=models.CharField(choices=[('none', 'None'), ('grammar', 'Grammar'), ('lexis', 'Lexis'), ('phonetics', 'Phonetics')], default='none', max_length=20),
        ),
    ]
